### ISSUE TITLE
Features of a Script Engine for Plugin Infrastructures

### ISSUE THREAD

**Issue by hastebrot** [jexler/grengine#1]
Hey,

we're migrating our plugin infrastructure &mdash; which is written in Ruby (for JRuby) &mdash; to Groovy. We consider Grengine or Netflix Hystrix (with Nicobar) as a convenience wrapper around the Groovy shell and started with the evaluation of both.

Our existing unit tests already have tests for `org.jruby.embed.ScriptingContainer` and `groovy.lang.GroovyShell`, which include:

- tests for evaluation of scripts,
- tests for java style imports of other scripts,
- tests for setting multiple root directories for scripts,
- tests for redirection of output streams,
- tests for exception handling,
- tests for execution of JUnit tests (and Spock specifications),
- tests for passing arguments to scripts and execution certain procedures, and
- tests for abort of script execution,
- tests for hot-swiching scripts at runtime.

The Groovy mailing list bounces my emails back, so I thought it's a good idea to simply create an issue here. :smile_cat:  We are willing to contribute the unit tests and add missing features in case of decision for Grengine.

--Benjamin

**Comment by jexler** [comment]
Hi Benjamin,

Wow an evaluation with Netflix Hystrix in the same boat :)

I did not know Nicobar, interesting...

Please do not hesitate to ask if something about Grengine is not clear or it is not clear how to use it best for your use cases. :) Nominally, it is built to be very heavily configurable, plus extensible by overriding classes or implementing interfaces. Some features may not have been sufficiently tested in "real-life situations", yet, which is why I am also eager to get feedback if something does not work as advertised etc.

Regarding the mailing list: Groovy has very recently moved from Codehaus to Apache, maybe the bouncing was related to that? http://www.groovy-lang.org/mailing-lists.html

Best wishes,
Alain

**Comment by jexler** [comment]
FYI, I have just a added new unit tests in a new GrengineGrapeTest, in the Grengine master branch, which implement basic interoperability tests of Grengine with Groovy Grape, i.e. the possibility to pull dependencies from Maven Repos at script runtime.

From a comment in the new test class:

 * In principle, a GroovyClassLoader (or a RootLoader) must be present
 * somewhere up the class loader parent hierarchy when using Grape to
 * pull external dependencies, else a RuntimeException is thrown with
 * message "No suitable ClassLoader found for grab".
 * 
 * With Grengine, a GroovyClassLoader is normally only used for compilation,
 * but not at runtime, so if Grape is needed, a GroovyClassLoader should
 * be set as parent of the LayeredEngine (or somewhere further up).

This works in the unit tests (with Groovy versions 1.7.5 and up) and seems robust in theory, but I cannot exclude for certain that some issues might still pop up in real life situations in a servlet container or similar.

On the other hand, depending on the use case, not allowing Grape in scripts might even be desirable from a security point of view, and with Grengine disabling this feature might thus be easier to customize within a Java VM than when using the GroovyShell etc.

**Comment by hastebrot** [comment]
Hi Alain,

Grape support sounds good. We definately have use cases for this.

For context: I work on a geographical information system (GIS) that currently contains more than 100 tools (e.g. geometric queries and analysis, statistical analysis, geometry editing, ...) implemented as precompiled plugins and runtime scripts with tests. We introduced support for runtime scripts and it improved our development workflow a lot. There are a lot generic GIS-related tool scripts and some specific tool scripts such as support for Excel export. Using Grape to add a Java library for Excel exports could simplify our development workflow and deployment even more.

>On the other hand, depending on the use case, not allowing Grape in scripts might even be desirable from a security point of view

I peeked through the tests in your recent commits, but didn't find a tests for this use case (disabling Grape). I think Grengine could for example throw an exception, if a Grape statement is used, but Grape support disabled.

>which is why I am also eager to get feedback if something does not work as advertised

I'll see what I can do. :smiley:

&mdash;Benjamin

**Comment by jexler** [comment]
Hi Benjamin,

The project sounds interesting :)

And yes, there is a test and, yes, an exception is thrown, it's the first test in GrengineGrapeTest.

FYI, I noticed one other thing with regard to Grape, namely that compiling is not thread-safe (down on the level of the Groovy compiler) if Grape is used: If two scripts that have the same Grape imports are compiled in separate threads, compilation may fail.

This seems to be because Groovy Grape resp. in combination with Apache Ivy is not thread safe. I have written to the Groovy dev mailing list, but people seem more busy with elementary things regarding project migration from Codehaus to Apache at the moment, at least nobody replied so far.

Currently, I see no way around this limitation with GroovyShell etc., but with Grengine it is possible! :)

Without a new release by overriding DefaultGroovyCompiler with a class that synchronizes the call "cu.compile(phase);" in the compile() method on some fairly global Object.

I am also considering to make this synchronization possible without having to override DefaultGroovyCompiler in a future Grengine release, and I already have a working implementation with unit tests, but I have not yet made up my mind if this is the most elegant way to go...

Even if Groovy or Ivy should fix the issue, I would still like to provide a workaround for older versions of Groovy and/or Ivy, unless, of course, there was a similarly simple workaround within the Groovy framework itself...

Best wishes,
Alain

**Comment by jexler** [comment]
FYI, after discussion on the dev mailing list, I filed a bug "Compilation not thread safe if Grape / Ivy is used in Groovy scripts": https://issues.apache.org/jira/browse/GROOVY-7407
Looks to me at the moment like no workaround is possible, before this is eventually fixed. If Grape is used, only one GroovyClassLoader that compiles/runs scripts that use Grape can be used concurrently. I am still pondering the possibility of an acceptable workaround with Grengine, but am not sure if it is possible.

**Comment by jexler** [comment]
Grengine 1.0.3
http://grengine.ch/relnotes.html
http://grengine.ch/manual.html#grengine-and-grape
(I found a workaround)

**Comment by jexler** [comment]
Hi Benjamin,

FYI, I just released version 1.0.4: http://groovy.329449.n5.nabble.com/ANN-Grengine-1-0-4-td5727237.html
Is the evaluation still ongoing? Any feedback? Should this issue remain open?

Best wishes,
Alain

**Comment by hastebrot** [comment]
Thanks for all the good work. Will close this issue and reopen it, when I find the time to continue the evaluation.
