### ISSUE TITLE
Can a Grengine instance shared across multiple threads?

### ISSUE THREAD

**Issue by pditommaso** [jexler/grengine#4]
Is it possible to share safely the same Grengine instance across multiple threads, having each thread invoke the `run` method for a different script / binding pair ?

**Comment by jexler** [comment]
The short answer is: Yes, definitely, Grengine has been designed for that. :)

A simple situation like this one works without doing anything special:

```Java
Grengine gren = new Grengine();
// in thread1
gren.run(scriptFile1, binding1);
// in thread2
gren.run(scriptFile2, binding2);
```

If you have a some utility scripts which have a *static state* with access that is not thread-safe, e.g.

```Groovy
class Util {
  static def state
  def modifyStateThrowsIfConcurrentAccess(...) { ... }
}
```

and do this:

```Java
Grengine gren = new Grengine(dirThatContainsUtilClass);
// in thread1
gren.run(scriptFile1ThatUsesUtil, binding1);
// in thread2
gren.run(scriptFile2ThatUsesUtil, binding2);
```

then this is not thread-safe, because Util.modifyStateThrowsIfConcurrentAccess() is not thread-safe and Util has been loaded by the same class loader in both threads.

Instead do this:

```Java
Grengine gren = new Grengine(dirThatContainsUtilScript);
// in thread1 once
Loader loader1 = gren.newAttachedLoader();
// in thread2 once
Loader loader2 = gren.newAttachedLoader();
// in thread1
gren.run(loader1, scriptFile1ThatUsesUtil, binding1);
// in thread2
gren.run(loader2, scriptFile2ThatUsesUtil, binding2);
```

This will make sure Util is loaded by different class loaders in the two threads, hence static variables are separate. (Note: Util is only *compiled once per Grengine instance* and loaded from the same compiled bytecode by the different class loaders per thread.)

There are unit tests that verify that these things work, at several levels.

Finally, if you use Grape, Grengine is not thread-safe, due to a bug in Grape/Ivy, unless you use the workaround, see:

http://grengine.ch/manual.html#grengine-and-grape

**Comment by pditommaso** [comment]
Cool. That's useful! Thanks a lot.
